#!/usr/bin/env bash
# cd into the calculi dir, and run this on linux.

uptime

echo; lscpu; echo; numactl --hardware; echo; numactl --show

echo; cabal build time-gb
perf stat -d $(cabal list-bin time-gb) "$@"
