#!/usr/bin/env bash
# cd into the calculi dir, and run this on linux. Arguments can specify GHC RTS options.

uptime

echo; lscpu; echo; numactl --hardware; echo; numactl --show

cabal build time-gb
perf stat -d $(cabal list-bin time-gb) +RTS "$@"
